### ISSUE TITLE
 Fatal error: Declaration of Lionix\EnvClient\Services\EnvClient::useGetter

### ISSUE THREAD

**Issue by abublihi** [lionix-team/envclient#1]
Hi, thank you for the great package.

` Whoops\Exception\ErrorException  : Declaration of Lionix\EnvClient\Services\EnvClient::useGetter(Lionix\EnvClient\Interfaces\EnvGetterInterface
 $getter): Lionix\EnvClient\Services\EnvClient must be compatible with Lionix\EnvClient\Interfaces\EnvClientInterface::useGetter(Lionix\EnvClient\
Interfaces\EnvGetterInterface $getter): Lionix\EnvClient\Interfaces\EnvClientInterface`

Can you please fix this error ^.

**Comment by vaawebdev** [comment]
The issue is fixed!
